CC=g++
CFLAGS=-I

SymmetricDifference: symmetricDifference.o symmetricDifferenceFunc.o
	$(CC) -std=c++11 -o SymmetricDifference symmetricDifference.o symmetricDifferenceFunc.o
clean:
	rm -rf *.o SymmetricDifference


